server:
  port: 8095
#  servlet:
#    context-path: "/cards"

spring:
  application:
    name: "cards"

  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    username: root
    password: root
  sql:
    init:
      mode: always

  jpa:
    show-sql: true
    #hibernate.ddl-auto: update


#  config:
#    import: "optional:configserver:http://localhost:8071/"

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithClient: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

endpoints:
  shutdown:
    enabled: true

logging:
  level:
    com:
      sbbank:
        cards: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

info:
  app:
    name: "Cards"
    description: "sbBank Card microservice instance"
    version: "1.0.0"


