server:
  port: 8072

spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"


  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 2s
      routes[0]:
        id: "ACCOUNTS"
        uri: "lb://ACCOUNTS"
        predicates[0]: "Path=/accounts/**"
#        metadata:
#          'cors':
#            allowedOrigins: '*'
#            allowedMethods:
#              - GET
#              - POST
#            allowedHeaders: '*'
#            maxAge: 30
      routes[1]:
        id: "LOANS"
        uri: "lb://LOANS"
        predicates[0]: "Path=/loans/**"
      routes[2]:
        id: "CARDS"
        uri: "lb://CARDS"
        predicates[0]: "Path=/cards/**"


#  config:
#    import: "optional:configserver:http://localhost:8071/"


eureka:
  instance:
    preferIpAddress: true

  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"


management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com:
      gatewayserver:
        cards: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}



info:
  app:
    name : "gatewayserver"
    description: "Edge server for sbBank application"
    version: "1.0.0"

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000