# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: loans-deployment
serviceName: loans
appLabel: loans
appName: loans
datasourceUrl: jdbc:mysql://loansdb.default.svc.cluster.local:3306/loansdb
datasourceUsername: root
datasourcePassword: root

replicaCount: 1

image:
  repository: shourav1211/loans
  tag: v1

containerPort: 8090

service:
  type: ClusterIP
  port: 8090
  targetPort: 8090

appname_enabled: true
profile_enabled: true
config_enabled: true
mysql_database_enabled: true
discovery_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: false