# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: accounts-deployment
serviceName: accounts
appLabel: accounts
appName: accounts
datasourceUrl: jdbc:mysql://accountsdb.default.svc.cluster.local:3306/accountsdb
datasourceUsername: root
datasourcePassword: root

replicaCount: 2

image:
  repository: shourav1211/accounts
  tag: v1

containerPort: 8085

service:
  type: ClusterIP
  port: 8085
  targetPort: 8085

appname_enabled: true
profile_enabled: true
config_enabled: true
mysql_database_enabled: true
discovery_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: true