spring:
  application:
    name: "configserver"

  profiles:
    #active: native {used for classpath or external file system approach}
    active: git
  cloud:
    config:
      server:
        #native:
          #search-locations: "classpath:/config"
          #search-locations: "file:///Users//shouravbhattarai//sbBank//config"
        git:
          uri: "https://github.com/ShouravB/sbBank-config.git"
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true

server:
  port: 8071

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

#encrypt:
 # key: "adfghbvh6hy89uhgsh0asd"


