server:
  port: 9010

spring:
  application:
    name: "message"
  cloud:
    function:
      definition: email|sms
    stream:
      bindings:
        emailsms-in-0:
          destination: send-email-sms
          group: ${spring.application.name}
        emailsms-out-0:
          destination: email-sms-sent
      kafka:
        binder:
          brokers: localhost
          defaultBrokerPort: 9092
          healthTimeout: 30
          autoCreateTopics: true

#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    connection-timeout: 10s